# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: Default

variables:
  pythonVersion: '3.9'

steps:
- script: |
    which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew install python@3.9
    python3.9 --version  # Check Python version
  displayName: 'Install Python 3.9 from Homebrew on macOS'



# - script: |
#     echo "Downloading Python release from GitHub..."
#     curl -H "Authorization: token $(GH_TOKEN)" -L -o python-release.tar.gz \
#       https://github.com/python/cpython/releases/download/v3/Python-3.tgz
#     tar -xvzf python-release.tar.gz
#   displayName: 'Download Python release from GitHub'

- script:
    python --version
  displayName: 'Check python version' 

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
  
